baseurl = "./"
languageCode = "en-us"
theme = "hugo-creative-theme"
googleAnalytics = "UA-2880668-17"

# SEO IMPORTANT
Title = "Nanotale - Typing Chronicles"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Nanotale - Typing Chronicles"
	# SEO IMPORTANT
	description = "Nanotale is the new adventure from the Typing Chronicles franchise and the spiritual successor to the acclaimed Epistory. Nanotale is currently in development at Fishing Cactus, the creator of Epistory - Typing Chronicles and Shift Quantum"
	# The path must be relative to the static folder
	favicon = "favicon2.ico"


	# Navigation
	[params.navigation]
		brand = "Nanotale - Typing Chronicles"

		[params.navigation.links]
			about     = "About"
			services  = "Screenshots"
			portfolio = ""
			aside = "Presskit"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.png' at './static/img' with your own.
		slogan     = ""
		logo       = "logo.png"
		subtitle   = ""
		buttonText = ""
		videoBG = "header.mp4"
		videoPoster = ""

	# About section
	[params.about]
		headline    = "Nanotale - Typing Chronicles"
		description = "Something is wrong with the heart of magic. Play a young archivist venturing out into a dying world, cataloging its mysteries and its wonders to unearth the truth. Nanotale is the new adventure from the Typing Chronicles franchise and the spiritual successor to the acclaimed [Epistory](https://store.steampowered.com/app/398850/Epistory__Typing_Chronicles/)."
		
		# video: Video can be set by adding a video.md in content file.
		# buttonText  = "OMG THIS IS AWESOME"


	# Service section
	[params.services]
		headline = "SCREENSHOTS"
		gallery = "true"


    # Aside section
	[params.aside]
		headline = "PRESSKIT"

		[params.aside.button]
			text = "Download now"
			link = "https://drive.google.com/open?id=1bvkHfgegGRb29cqfLkOVEdXte2cHH6Fe"

	# Contact section
	[params.contact]
		headline = "GET IN TOUCH!"
		description = "Join our [Discord](https://discord.gg/KqtBnHM) channel and chat in live with the team."
		twitter = "Nanotalegame"
		twitterSVG = "TW_icon.png"
		facebook = "Nanotalegame"
		facebookSVG = "FB_icon.png"
		discord = "KqtBnHM"
		discordSVG = "DIS_icon.png"
		email = "nanotale@fishingcactus.com"
		emailSVG = "ML_icon.png"

		[params.contact.subscribe]
			actionURL = "http://fishingcactusnews.createsend.com/t/d/s/ikdukk/"
			description = "SUBSCRIBE TO OUR MAILING LIST BELOW"
			inputName = "cm-ikdukk-ikdukk"
			buttonText = "SUBSCRIBE"

	# Portfolio section
	[Data.projects]
		headline = ""
		europe = "logo_europe.png"

	# Footer section
	[params.footer]
		copyright = ""
